### ISSUE TITLE
Smaller binary size

### ISSUE THREAD

**Issue by noplanman** [dgmid/nextcloud-notes-mac-client#3]
I'd love to give your apps a try, but being over 100MB for something as simple as editing notes (or bookmarks) just feels so wrong to me.

As I'm completely unfamiliar with Electron and it's development, all I can do is ask if using something like [Electrino](https://medium.com/dailyjs/put-your-electron-app-on-a-diet-with-electrino-c7ffdf1d6297) is possible and viable.

Hope you understand what I mean :blush:

**Comment by dgmid** [comment]
I understand your point, the Electron footprint is rather large.
I wrote these app solely because they didn't exist and I needed them. 

Electron is simply the quickest way I could do that. Electrino sound like a good idea in principle - but it seems to just be a proof of concept and nowhere near production ready.

That being said - my main reason for sharing these apps on GitHub is so that anyone can take them and do what they want to them.

(I would have called it Neutrino! 😉)

**Comment by noplanman** [comment]
@dgmid Right, I understand, thanks for explaining!

Well if you ever feel inspired to explore smaller file sizes, you have at least 1 person who will cheer you on :tada: :wink:
